import Zeta23.Research.JensenWedge.XiNaturalMultiplierCertificate

#print axioms Zeta23.Research.JensenWedge.xiNaturalConcreteMultiplier_six_nodes
#print axioms Zeta23.Research.JensenWedge.xiNaturalConcreteMultiplier_sub_one_norm_lt_one_on_tube
#print axioms Zeta23.Research.JensenWedge.xiNaturalConcreteRealMultiplier_six_nodes_of_explicitCutoff
#print axioms Zeta23.Research.JensenWedge.xiNaturalActualComparison_relativeError_lt_one_at_critical
#print axioms Zeta23.Research.JensenWedge.multiplierIntervalCertificate_of_complete_roots
#print axioms Zeta23.Research.JensenWedge.MultiplierIntervalCertificate.actual_hasDistinctPositiveRoots
#print axioms Zeta23.Research.JensenWedge.xiNatural_multiplierIntervalCertificate
#print axioms Zeta23.Research.JensenWedge.xiNatural_jensenWedgeCertificate
#print axioms Zeta23.Research.JensenWedge.xiNaturalActualLogPolynomial_eq_comparisonMultiplierTransform_of_explicitCutoff
#print axioms Zeta23.Research.JensenWedge.xiNaturalActualLogPolynomial_roots_to_riemannXi
#print axioms Zeta23.Research.JensenWedge.riemannXiJensen_twoThirds_low_degree
#print axioms Zeta23.Research.JensenWedge.riemannXiJensen_twoThirds_headline
